* Mercury Core
*Mercury Core* is a Network and Storage manager for the [[https://github.com/nexhero/mercury][Mercury Note App]] . This repository provides the core functionality that powers Mercury's decentralized storage and networking capabilities.

*Features*
- Network Management: Handling of peer-to-peer connections.
- Storage Management: Use hyperbee and autobase for data storage solutions for Mercury notes.
- JavaScript-Powered: Entirely built in JavaScript for seamless integration and extensibility.

* Installation
To get started.

#+begin_src bash
npm i mercury-core
#+end_src

* Contributing
We welcome contributions to Mercury Core! To contribute:
1. Fork the repository.
2. Create a new branch for your feature or fix.
3. Commit your changes and push them to your fork.
4. Submit a pull request for review.

* License
This project is licensed under the MIT License

* Contact
For questions or support, reach out to the repository maintainers via [[https://github.com/nexhero/mercury-core/issues][GitHub Issues]].
